openapi: 3.0.0
info:
  title: Simulate API
  version: 1.0.0
paths:
  /simulate:
    post:
      summary: Run a symbolic multi-agent simulation
      operationId: simulate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                steps:
                  type: integer
                  default: 10
                  description: Number of time steps in the simulation
      responses:
        '200':
          description: Agent histories over time
          content:
            application/json:
              schema:
                type: object
                properties:
                  history:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: integer
